//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigatingMelbourne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChineseRestaurant
    {
        public int Id { get; set; }
        public string Year { get; set; }
        public string Block { get; set; }
        public string Prop_Id { get; set; }
        public string Bp_Id { get; set; }
        public string St_Address { get; set; }
        public string Small_Area { get; set; }
        public string Restaurant_name { get; set; }
        public string Ind_code_ { get; set; }
        public string Ind_desc { get; set; }
        public string Seating_Category { get; set; }
        public string Total_Seats__ { get; set; }
        public string x_coord { get; set; }
        public string y_coord { get; set; }
        public string Location { get; set; }
    }
}
