//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigatingMelbourne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI
    {
        public int Id { get; set; }
        public string Census_Year { get; set; }
        public string Block_ID { get; set; }
        public string Property_ID { get; set; }
        public string Base_property_ID { get; set; }
        public string Street_address { get; set; }
        public string CLUE_small_area { get; set; }
        public string Trading_name { get; set; }
        public string Industry_ANZSIC4_code_ { get; set; }
        public string Industry_ANZSIC4_description { get; set; }
        public string Seating_type { get; set; }
        public string Number_of_seats__ { get; set; }
        public string x_coordinate { get; set; }
        public string y_coordinate { get; set; }
        public string Location { get; set; }
    }
}
