//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigatingMelbourne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supermarket
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string Name { get; set; }
        public string Icode { get; set; }
        public string Idesc { get; set; }
        public string Seating_type { get; set; }
        public string Seats { get; set; }
        public string x_coordinate { get; set; }
        public string Location { get; set; }
    }
}
